const SIDEBAR_CONTENT = [
    {
      "langId": 1,
      "langName": "Java",
      "techName": "Core Java",
      "tuCount": 223,
      "mcqCount": 668,
      "iqCount": 432,
      "csCount": 543,
      "weight": 44,
      "icon": "java",
      "topics": [
        {
          "topicId": 1,
          "techId": 1,
          "topicName": "Basics",
          "pqCount": 86,
          "iqCount": 30,
          "csCount": 42,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 2
        },
        {
          "topicId": 2,
          "techId": 1,
          "topicName": "Data Type",
          "pqCount": 65,
          "iqCount": 11,
          "csCount": 284,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 3
        },
        {
          "topicId": 3,
          "techId": 1,
          "topicName": "Control Statement",
          "pqCount": 38,
          "iqCount": 0,
          "csCount": 64,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 2
        },
        {
          "topicId": 4,
          "techId": 1,
          "topicName": "Operators",
          "pqCount": 45,
          "iqCount": 0,
          "csCount": 44,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 6,
          "techId": 1,
          "topicName": "Arrays",
          "pqCount": 152,
          "iqCount": 11,
          "csCount": 36,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 7,
          "techId": 1,
          "topicName": "OOPs",
          "pqCount": 12,
          "iqCount": 13,
          "csCount": 29,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 8
        },
        {
          "topicId": 8,
          "techId": 1,
          "topicName": "Interfaces",
          "pqCount": 5,
          "iqCount": 0,
          "csCount": 2,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 9,
          "techId": 1,
          "topicName": "Enums",
          "pqCount": 10,
          "iqCount": 0,
          "csCount": 6,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 4
        },
        {
          "topicId": 10,
          "techId": 1,
          "topicName": "Packages",
          "pqCount": 13,
          "iqCount": 0,
          "csCount": 8,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 2
        },
        {
          "topicId": 11,
          "techId": 1,
          "topicName": "Keywords",
          "pqCount": 5,
          "iqCount": 0,
          "csCount": 18,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 3
        },
        {
          "topicId": 12,
          "techId": 1,
          "topicName": "Wrapper Classes",
          "pqCount": 60,
          "iqCount": 0,
          "csCount": 34,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 1
        },
        {
          "topicId": 13,
          "techId": 1,
          "topicName": "Nested Classes",
          "pqCount": 57,
          "iqCount": 23,
          "csCount": 78,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 2
        },
        {
          "topicId": 14,
          "techId": 1,
          "topicName": "Exception",
          "pqCount": 26,
          "iqCount": 0,
          "csCount": 26,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 15,
          "techId": 1,
          "topicName": "String",
          "pqCount": 12,
          "iqCount": 0,
          "csCount": 26,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 6
        },
        {
          "topicId": 16,
          "techId": 1,
          "topicName": "AWT",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 25,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 17,
          "techId": 1,
          "topicName": "Event",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 10,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 18,
          "techId": 1,
          "topicName": "Swing",
          "pqCount": 51,
          "iqCount": 8,
          "csCount": 21,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 19,
          "techId": 1,
          "topicName": "Threading",
          "pqCount": 0,
          "iqCount": 1,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 20,
          "techId": 1,
          "topicName": "Concurrency",
          "pqCount": 15,
          "iqCount": 0,
          "csCount": 78,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 21,
          "techId": 1,
          "topicName": "Input Output",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 14,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 22,
          "techId": 1,
          "topicName": "Networking",
          "pqCount": 70,
          "iqCount": 23,
          "csCount": 91,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 23,
          "techId": 1,
          "topicName": "Collection",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 13,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 10
        },
        {
          "topicId": 24,
          "techId": 1,
          "topicName": "Stream API",
          "pqCount": 0,
          "iqCount": 1,
          "csCount": 16,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 25,
          "techId": 1,
          "topicName": "Regex API",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 10,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 5
        },
        {
          "topicId": 26,
          "techId": 1,
          "topicName": "Date-Time API",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 1,
          "spf": 0,
          "weight": 3
        },
        {
          "topicId": 27,
          "techId": 1,
          "topicName": "Reflection API",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 4,
          "crf": 1,
          "fsf": 1,
          "spf": 0,
          "weight": 2
        },
        {
          "topicId": 28,
          "techId": 1,
          "topicName": "I18N",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 13,
          "crf": 1,
          "fsf": 1,
          "spf": 0,
          "weight": 1
        },
        {
          "topicId": 29,
          "techId": 1,
          "topicName": "JDK9 and JDK10",
          "pqCount": 19,
          "iqCount": 0,
          "csCount": 15,
          "crf": 1,
          "fsf": 1,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 30,
          "techId": 1,
          "topicName": "JDK11",
          "pqCount": 20,
          "iqCount": 0,
          "csCount": 43,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 31,
          "techId": 1,
          "topicName": "JDK12 and JDK13",
          "pqCount": 58,
          "iqCount": 0,
          "csCount": 48,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 32,
          "techId": 1,
          "topicName": "JDK14 and JDK15",
          "pqCount": 22,
          "iqCount": 0,
          "csCount": 23,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 33,
          "techId": 1,
          "topicName": "JDK16 and JDK17",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 24,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 1
    },
    {
      "langId": 1,
      "langName": "Java",
      "techName": "JDBC",
      "tuCount": 0,
      "mcqCount": 44,
      "iqCount": 0,
      "csCount": 0,
      "weight": 0,
      "icon": "jdbc",
      "topics": [
        {
          "topicId": 34,
          "techId": 2,
          "topicName": "JDBC Basics",
          "pqCount": 36,
          "iqCount": 0,
          "csCount": 30,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 35,
          "techId": 2,
          "topicName": "JDBC Driver Types",
          "pqCount": 8,
          "iqCount": 0,
          "csCount": 6,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 36,
          "techId": 2,
          "topicName": "JDBC APIs",
          "pqCount": 14,
          "iqCount": 0,
          "csCount": 10,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 37,
          "techId": 2,
          "topicName": "SQL Basics",
          "pqCount": 6,
          "iqCount": 0,
          "csCount": 7,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 38,
          "techId": 2,
          "topicName": "JDBC Techniques",
          "pqCount": 10,
          "iqCount": 0,
          "csCount": 4,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 2
    },
    {
      "langId": 1,
      "langName": "Java",
      "techName": "Servlet",
      "tuCount": 0,
      "mcqCount": 23,
      "iqCount": 0,
      "csCount": 0,
      "weight": 0,
      "icon": "servlet",
      "topics": [
        {
          "topicId": 39,
          "techId": 3,
          "topicName": "Servlet Basics",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 2,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 40,
          "techId": 3,
          "topicName": "Collaboration",
          "pqCount": 46,
          "iqCount": 0,
          "csCount": 11,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 41,
          "techId": 3,
          "topicName": "Session Tracking",
          "pqCount": 15,
          "iqCount": 0,
          "csCount": 13,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 42,
          "techId": 3,
          "topicName": "Servlet Filter",
          "pqCount": 10,
          "iqCount": 0,
          "csCount": 14,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 43,
          "techId": 3,
          "topicName": "Servlet Listeners",
          "pqCount": 5,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 44,
          "techId": 3,
          "topicName": "Mini Projects",
          "pqCount": 5,
          "iqCount": 0,
          "csCount": 13,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 3
    },
    {
      "langId": 1,
      "langName": "Java",
      "techName": "JSP",
      "tuCount": 0,
      "mcqCount": 65,
      "iqCount": 0,
      "csCount": 0,
      "weight": 0,
      "icon": "jsp",
      "topics": [
        {
          "topicId": 45,
          "techId": 4,
          "topicName": "JSP Basics",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 11,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 46,
          "techId": 4,
          "topicName": "JSP Directives",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 47,
          "techId": 4,
          "topicName": "JSP Actions",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 1,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 48,
          "techId": 4,
          "topicName": "JSP Expression",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 1,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 49,
          "techId": 4,
          "topicName": "JSP Custom Tag",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 50,
          "techId": 4,
          "topicName": "JSTL",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 51,
          "techId": 4,
          "topicName": "JSP Projects",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 4
    },
    {
      "langId": 1,
      "langName": "Java",
      "techName": "Spring",
      "tuCount": 0,
      "mcqCount": 44,
      "iqCount": 0,
      "csCount": 0,
      "weight": 0,
      "icon": "spring",
      "topics": [
        {
          "topicId": 55,
          "techId": 8,
          "topicName": "Spring Core",
          "pqCount": 0,
          "iqCount": 50,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 56,
          "techId": 8,
          "topicName": "Spring MVC",
          "pqCount": 10,
          "iqCount": 0,
          "csCount": 57,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 57,
          "techId": 8,
          "topicName": "Spring ORM",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 32,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 58,
          "techId": 8,
          "topicName": "Spring AOP",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 59,
          "techId": 8,
          "topicName": "Spring JDBC",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 4,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 60,
          "techId": 8,
          "topicName": "Spring TM",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 10,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 61,
          "techId": 8,
          "topicName": "Spring Security",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 62,
          "techId": 8,
          "topicName": "Spring OXM",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 8,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 63,
          "techId": 8,
          "topicName": "Spring Remoting",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 64,
          "techId": 8,
          "topicName": "Spring SPEL",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 6,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 65,
          "techId": 8,
          "topicName": "Spring Mail",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 66,
          "techId": 8,
          "topicName": "Spring Batch",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 6,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 67,
          "techId": 8,
          "topicName": "Spring WebService",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 6,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 68,
          "techId": 8,
          "topicName": "Spring Cloud",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 12,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 69,
          "techId": 8,
          "topicName": "Spring Quartz",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 1,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 8
    },
    {
      "langId": 1,
      "langName": "Java",
      "techName": "Spring Boot",
      "tuCount": 0,
      "mcqCount": 65,
      "iqCount": 0,
      "csCount": 0,
      "weight": 0,
      "icon": "springboot",
      "topics": [
        {
          "topicId": 83,
          "techId": 9,
          "topicName": "SB Basics",
          "pqCount": 0,
          "iqCount": 11,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 84,
          "techId": 9,
          "topicName": "SB Starters",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 85,
          "techId": 9,
          "topicName": "SB Components",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 86,
          "techId": 9,
          "topicName": "SB Tools",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 87,
          "techId": 9,
          "topicName": "SB AOP",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 88,
          "techId": 9,
          "topicName": "SB with Database",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 89,
          "techId": 9,
          "topicName": "SB Caching",
          "pqCount": 6,
          "iqCount": 0,
          "csCount": 1,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 90,
          "techId": 9,
          "topicName": "Spring Boot RESTful",
          "pqCount": 1,
          "iqCount": 0,
          "csCount": 1,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        },
        {
          "topicId": 91,
          "techId": 9,
          "topicName": "SB Security",
          "pqCount": 0,
          "iqCount": 0,
          "csCount": 0,
          "crf": 0,
          "fsf": 0,
          "spf": 0,
          "weight": 0
        }
      ],
      "Id": 9
    }
  ]